# 服务定义
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-12080}:13001"
    volumes:
      - /you/path:/app/photos
      - ./data:/app/data
    container_name: Photonix
    env_file:
      - ./.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:13001/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 20s
      timeout: 15s
      retries: 3
      start_period: 120s
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - photonix-network
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G

  redis:
    # Redis 服务，缓存和消息队列
    image: redis:7-alpine
    container_name: Photonix-redis
    ports:
      - "6379:6379"  # 映射 Redis 端口
    command: redis-server --appendonly yes  # 开启持久化
    volumes:
      - redis_data:/data  # Redis 数据持久化卷
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]  # 健康检查
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - photonix-network


# 卷定义
volumes:
  redis_data:  # Redis 数据卷

# 网络定义
networks:
  photonix-network:
    driver: bridge  # 桥接网络